### ISSUE TITLE
unable to start

### ISSUE THREAD

**Issue by ghost** [TimurKiyivinski/crypt-monitor#1]
[npm-debug.txt](https://github.com/TimurKiyivinski/crypt-monitor/files/580904/npm-debug.txt)

**Comment by kiyui** [comment]
Have you tried rebuilding your `node_modules/` folder? Try removing it and running `npm install` again.

**Comment by ghost** [comment]
The error persists.
Even tried on a different machine running Ubuntu 16.04

**Comment by kiyui** [comment]
I'm closing this issue as the application has already been tested on multiple distros and even works inside a Docker container.
